

export const USERLOGINREQ = "USERLOGINREQ"
export const USERLOGINRES = "USERLOGINRES"
export const USERLOGINREJ = "USERLOGINREJ"


export const USERLOGOUTREQ = "USERLOGOUTREQ"
export const USERLOGOUTRES = "USERLOGOUTRES"
export const USERLOGOUTREJ = "USERLOGOUTREJ"

export const USERSIGNINGOOGLEPOPUPREQ = "USERSIGNINGOOGLEPOPUPREQ"
export const USERSIGNINGOOGLEPOPUPRES = "USERSIGNINGOOGLEPOPUPRES"
export const USERSIGNINGOOGLEPOPUPREJ = "USERSIGNINGOOGLEPOPUPREJ"


// Form creation

export const PRODUCTREQ = "PRODUCTREQ"
export const PRODUCTSUC = "PRODUCTSUC"
export const PRODUCTREJ = "PRODUCTREJ"

export const SINGLEDATAREQ = "SINGLEDATAREQ"
export const SINGLEDATARES = "SINGLEDATARES"
export const SINGLEDATAREJ = "SINGLEDATAREJ"

export const UPDATEREQ = "UPDATEREQ"
export const UPDATERES = "UPDATERES"
export const UPDATEREJ = "UPDATEREJ"

export const DELETEDATAREQ = "DELETEDATAREQ";
export const DELETEDATAREJ = "DELETEDATAREJ";


export const CREATELOGINREQ = "CREATELOGINREQ";
export const CREATELOGINREJ = "CREATELOGINREJ";
