// Form creation

export const PRODUCTREQ = "PRODUCTREQ"
export const PRODUCTSUC = "PRODUCTSUC"
export const PRODUCTREJ = "PRODUCTREJ"

export const SINGLEDATAREQ = "SINGLEDATAREQ"
export const SINGLEDATARES = "SINGLEDATARES"
export const SINGLEDATAREJ = "SINGLEDATAREJ"


// Authentication

export const USERSIGNUPREQ = "USERSIGNUPREQ"
export const USERSIGNUPRES = "USERSIGNUPRES"
export const USERSIGNUPREJ = "USERSIGNUPREJ"

export const USERLOGINREQ = "USERLOGINREQ"
export const USERLOGINRES = "USERLOGINRES"
export const USERLOGINREJ = "USERLOGINREJ"


export const USERLOGOUTREQ = "USERLOGOUTREQ"
export const USERLOGOUTRES = "USERLOGOUTRES"
export const USERLOGOUTREJ = "USERLOGOUTREJ"

export const USERSIGNINGOOGLEPOPUPREQ = "USERSIGNINGOOGLEPOPUPREQ"
export const USERSIGNINGOOGLEPOPUPRES = "USERSIGNINGOOGLEPOPUPRES"
export const USERSIGNINGOOGLEPOPUPREJ = "USERSIGNINGOOGLEPOPUPREJ"


export const CREATELOGINREQ = "CREATELOGINREQ";
export const CREATELOGINREJ = "CREATELOGINREJ";

export const GETLOGINUSERDATAREQ = "GETLOGINUSERDATAREQ"
export const GETLOGINUSERDATARES = "GETLOGINUSERDATARES"
export const GETLOGINUSERDATAREJ = "GETLOGINUSERDATAREJ"


// itemTypes.js
export const ADD_TO_CART = 'ADD_TO_CART';

